CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    category_key VARCHAR(50) NOT NULL DEFAULT 'medium'
        REFERENCES categories(key) ON UPDATE CASCADE ON DELETE RESTRICT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    pomodoro_count INTEGER NOT NULL DEFAULT 0,
    total_seconds INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
